import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Link from "next/link"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Selasie | Software Engineer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="px-10">
      <body className={`${inter.className} body`}>
      <Header/>
        {children}
        <footer className="flex justify-between items-center my-10">
        <div className="flex justify-center items-start gap-3">
          <span className="text-white text-xl">
            <Link href="">
            Github
            </Link>
          </span> {" "} <span className="text-white">|</span> {" "}
          <span className="text-white text-xl">
            <Link href="">
            Linkedin
            </Link>
          </span> {" "} <span className="text-white">|</span> {" "}
          <span className="text-white text-xl">
            <Link href="">
            Twitter
            </Link>
          </span> {" "} <span className="text-white">|</span> {" "}
          <span className="text-white text-xl">
            <Link href="">
            Email
            </Link>
          </span> 
        </div>
<span className="text-white">Designed and developed by Selasie Sepenu</span>
      </footer>
        </body>
    </html>
  );
}
