import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react"
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Link from "next/link"
import Footer from "./components/Footer"
import CustomCursor from "./components/CustomCursor";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Selasie | Software Engineer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="px-10">
      <body className={`${inter.className} body`}>
        <CustomCursor/>
      <Header/>
        {children}
        <Analytics/>
       <Footer/>
        </body>
    </html>
  );
}
